### ISSUE TITLE
singleViewStyle = "caspertwo" does not show categories

### ISSUE THREAD

**Issue by srigurubyo** [eueung/hugo-casper-two#13] opened 2018-04-25 13:58 UTC
Setting singleViewStyle = "caspertwo"  doesn't show categories and I get blank page.  Any clue?

However singleViewStyle = "caspertwo" shows them properly.

**Comment by srigurubyo** [comment] 2018-04-25 13:59
However   singleViewStyle = "casper" shows categories properly.

**Comment by srigurubyo** [comment] 2018-04-25 14:00
Sorry closed this by mistake.

**Comment by shnek** [comment] 2018-04-27 15:34
Can you elaborate more on this issue? You said that setting singleViewStyle to the same "caspertwo" does two different things. What is the blank page you get, the post page or index page?

**Comment by srigurubyo** [comment] 2018-04-27 16:30
setting it as casper shows categories properly.

However setting it as caspertwo does not show any categories on the URL
/categories.

Hope I am clear now.

Thanks a lot for your kind response.

**Comment by shnek** [comment] 2018-04-30 13:49
@srigurubyo Thank you for the explanation. I was able to reproduce the issue.
I have forked this repository and worked on the fix for that. I just ported the same taxonomy page (which you can see in the "casper" theme) to caspertwo. I have also created a pull request to have that changes merged into the main repository.
If you want to check out the modified theme, here is the link:
https://github.com/shnek/hugo-casper-two/tree/Taxonomy-fix
If you have any further questions feel free to ask and I'll do my best to answer them.

**Comment by srigurubyo** [comment] 2018-04-30 15:22
Great, thanks a lot.

Special thanks to you for making this wonderful theme!

All the best wishes

**Comment by srigurubyo** [comment] 2018-05-01 13:58
@shnek, I have another query/request regarding this theme.

Is there a way we can assign individual weights to posts (tags) or categories to display them in a particular order?

Say, I want xyz to appear first always.

(PS: I have created another separate issue for this, please free to close that if you feel so.)

**Comment by shnek** [comment] 2018-05-01 15:50
Since you created a separate issue, I commented my findings on that thread. If you have any further questions, I'd be glad to answer them there!

**Comment by srigurubyo** [comment] 2018-05-02 03:13
Thank you @shnek

Really appreciate the time taken to answer my queries and the help provided.  

Best wishes!

**Closed as completed** 2018-05-02 03:13 UTC
